name: deploy-shiny

on:
  schedule:
    - cron: '0 4 */4 * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    steps:
    # zkopírování repozitory
      - uses: actions/checkout@v2
    
    # instalace R
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.5'
    
    # instalace závislostí
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
            
    # cache nainstalovaných knihoven
      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-etl
          restore-keys: |
            ${{ runner.os }}-
    
    # instalace knihoven (pokud nejsou v cache)
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: Rscript -e "install.packages(c('dplyr', 'glue', 'jsonlite', 'openxlsx', 'readr', 'rsconnect', 'shiny', 'stringr', 'tidyr'))"
    
    # aktualizace dat
      - name: Update data
        run: Rscript -e "source('R/etl.R')"
        working-directory: ./shiny_plan
    
    # nasazeni do shinyapps.io
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='egov', token=${{secrets.EGOV_SHINYAPPS_TOKEN}}, secret=${{secrets.EGOV_SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appFileManifest = 'data/fileManifest.txt', appName = 'plan_digitalizace')"
        working-directory: ./shiny_plan
