name: deploy-shiny

on:
  schedule:
    - cron: '0 4 */4 * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    steps:
    # zkopírování repozitory
      - uses: actions/checkout@v2
    
    # instalace R
      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          use-public-rspm: true
    
    # instalace závislostí a knihoven
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: rcmdcheck
    
    # kontrola instalace závislostí a knihoven
      - name: Check package
        uses: r-lib/actions/check-r-package@v2
    
    # aktualizace dat
      - name: Update data
        run: Rscript -e "source('R/etl.R')"
        working-directory: ./shiny_plan
    
    # nasazeni do shinyapps.io
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='egov', token=${{secrets.EGOV_SHINYAPPS_TOKEN}}, secret=${{secrets.EGOV_SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appFileManifest = 'data/fileManifest.txt', appName = 'plan_digitalizace')"
        working-directory: ./shiny_plan
