name: deploy-shiny

on:
  schedule:
    - cron: '0 4 */4 * *'
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    steps:
    # zkopírování repozitory
      - uses: actions/checkout@v2
    
    # instalace R
      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.5'
    
    # instalace závislostí
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
            
    # instalace knihoven pomocí renv
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
    
    # aktualizace dat
      - name: Update data
        run: Rscript -e "source('R/etl.R')"
        working-directory: ./shiny_plan
    
    # nasazeni do shinyapps.io
      - name: Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='egov', token=${{secrets.EGOV_SHINYAPPS_TOKEN}}, secret=${{secrets.EGOV_SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appFileManifest = 'data/fileManifest.txt', appName = 'plan_digitalizace')"
        working-directory: ./shiny_plan
